logging:
  level:
    root: info

app:
  doc:
    enabled: true
  datasource:
    db-name:
      host: ${db-name}
      username: ${db-username}
      password: ${db-password}
  allowedOrigins:
    - "http://localhost:8080"
    - "http://localhost:3000"