spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
app:
  doc:
    enabled: true
  datasource:
    db-name:
      host: ${db-name}
      username: ${db-username}
      password: ${db-password}
  service:
    google:
      maps:
        url: ${GOOGLE_API_URL}
        key: ${GOOGLE_API_KEY}
  allowedOrigins:
    - "http://localhost:8080"
    - "http://localhost:3000"